id: I600507B0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-15T17:05:26+00:00'
last_modified: '2022-06-14T08:23:22.262729+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22379
  title: གཞུང་ཆེན་བཀའ་པོད་ལྔའི་རྩ་བ།
  author: ''
  base:
    6A10:
      image_group_id: I1KG22400
      title: ''
      total_pages: ''
      order: 1
      base_file: 6A10.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
